[package]
name = "actix_web_server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.0.0-beta.8", default-features = false }
ajars = { path = "../../ajars", features = ["actix_web"] }
ajars_common = { path = "../ajars_common" }
chrono = "0.4"