[package]
name = "ajars_common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ajars = { path = "../.." }
serde =  { version = "1.0", features = ["derive"] }