[workspace]

members = [
    "ajars_core",
    "ajars_actix_web",
    "ajars_axum",
    "ajars_reqwest",
    "ajars_surf",
    "ajars_warp",
    "ajars_web",
    "ajars",
    "examples/ajars_common",
    "examples/client_reqwest",
    "examples/client_surf",
    "examples/client_web_yew",
    "examples/server_actix_web",
] 
