[package]
name = "ajars"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
actix-web = { version = "4.0.0-beta.8", default-features = false, optional = true}
reqwest = { version = "0.11", default-features = false, features = ["json"], optional = true}

[dev-dependencies]
actix-rt = "2"
port_check = "0.1"
rand = "0.8"
#tokio = { version = "1", features = ["full"]}

[features]
client_reqwest = ["reqwest"]
server_actix_web = ["actix-web"]