[workspace]

members = [
    "ajars_core",
    "ajars_actix_web",
    "ajars_reqwest",
    "ajars_surf",
    "ajars_web_sys",
    "ajars",
    "examples/ajars_common",
    "examples/client_reqwest",
    "examples/client_surf",
    "examples/server_actix_web",
    "examples/web_yew_reqwest",
    "examples/web_yew_surf",
    "examples/web_yew_web_sys",
] 
